# SPDX-FileCopyrightText: 2022 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: SonarCloud Analysis

on: 
  workflow_run:
    workflows: [SonarCloud Build]
    types: [completed]

jobs:
  sonar-check:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    timeout-minutes: 15
    steps:
    - name: echo event
      run: cat $GITHUB_EVENT_PATH
    - name: Download PR number artifact
      if: github.event.workflow_run.event == 'pull_request' || (github.event.workflow_run.actor.type == 'Bot' && github.event.workflow_run.actor.login == 'dependabot[bot]' && github.event.workflow_run.event == 'pull_request_target')
      uses: dawidd6/action-download-artifact@5c98f0b039f36ef966fdb7dfa9779262785ecb05 # v14
      with:
        workflow: SonarCloud Build
        run_id: ${{ github.event.workflow_run.id }}
        name: PR_NUMBER
    - name: Read PR_NUMBER.txt
      if: github.event.workflow_run.event == 'pull_request' || (github.event.workflow_run.actor.type == 'Bot' && github.event.workflow_run.actor.login == 'dependabot[bot]' && github.event.workflow_run.event == 'pull_request_target')
      id: pr_number
      uses: juliangruber/read-file-action@b549046febe0fe86f8cb4f93c24e284433f9ab58 # v1
      with:
        path: ./PR_NUMBER.txt
    - name: Request GitHub API for PR data
      if: github.event.workflow_run.event == 'pull_request' || (github.event.workflow_run.actor.type == 'Bot' && github.event.workflow_run.actor.login == 'dependabot[bot]' && github.event.workflow_run.event == 'pull_request_target')
      uses: octokit/request-action@dad4362715b7fb2ddedf9772c8670824af564f0d # v2.4.0
      id: get_pr_data
      with:
        route: GET /repos/{full_name}/pulls/{number}
        number: ${{ steps.pr_number.outputs.content }}
        full_name: ${{ github.event.repository.full_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        repository: ${{ github.event.repository.full_name }}
        ref: ${{ github.event.workflow_run.head_sha }}
        fetch-depth: 0
    - name: Checkout base branch
      if: github.event.workflow_run.event == 'pull_request' || (github.event.workflow_run.actor.type == 'Bot' && github.event.workflow_run.actor.login == 'dependabot[bot]' && github.event.workflow_run.event == 'pull_request_target')
      env:
        CLONE_URL: ${{ github.event.repository.clone_url }}
        BASE_REF: ${{ fromJson(steps.get_pr_data.outputs.data).base.ref }}
        HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
      run: |
        git remote add upstream "$CLONE_URL"
        git fetch upstream
        git checkout -B "$BASE_REF" "upstream/$BASE_REF"
        git checkout "$HEAD_BRANCH"
        git clean -ffdx && git reset --hard HEAD
    - name: Cache SonarCloud packages
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up JDK 17
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Set Common Sonar Variables
      id: sonar_env
      run: |
        echo "##[set-output name=sonar_opts;]$(echo -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.projectKey=com-pas_compas-scl-data-service \
          -Dsonar.organization=com-pas )"
    - name: Create custom Maven Settings.xml
      uses: whelk-io/maven-settings-xml-action@9dc09b23833fa9aa7f27b63db287951856f3433d # v22
      with:
        output_file: custom_maven_settings.xml
        servers: '[{ "id": "github-packages-compas", "username": "OWNER", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
    - name: Build and analyze (Pull Request)
      if: ${{ github.event.workflow_run.event == 'pull_request' || (github.event.workflow_run.actor.type == 'Bot' && github.event.workflow_run.actor.login == 'dependabot[bot]' && github.event.workflow_run.event == 'pull_request_target') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_OPTS: ${{ steps.sonar_env.outputs.sonar_opts }}
        PR_HEAD_REF: ${{ fromJson(steps.get_pr_data.outputs.data).head.ref }}
        PR_NUMBER: ${{ fromJson(steps.get_pr_data.outputs.data).number }}
        PR_BASE_REF: ${{ fromJson(steps.get_pr_data.outputs.data).base.ref }}
        HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
      run: |
        ./mvnw -B -s custom_maven_settings.xml -Psonar \
          $SONAR_OPTS \
          -Dsonar.pullrequest.branch="$PR_HEAD_REF" \
          -Dsonar.pullrequest.key="$PR_NUMBER" \
          -Dsonar.pullrequest.base="$PR_BASE_REF" \
          -Dsonar.scm.revision="$HEAD_SHA" \
          clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
    - name: Build and analyze (Push)
      if: ${{ github.event.workflow_run.event == 'push' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_OPTS: ${{ steps.sonar_env.outputs.sonar_opts }}
        HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
        HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
      run: |
        ./mvnw -B -s custom_maven_settings.xml -Psonar \
          $SONAR_OPTS \
          -Dsonar.scm.revision="$HEAD_SHA" \
          -Dsonar.branch.name="$HEAD_BRANCH" \
          clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
